services:
  backend:
    build: 
      context: ./quizserver
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/quizdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db

  frontend:
    build:
      context: ./quizWeb
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=quizdb
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"    # Changed from 3306:3306 to 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: