name: Frontend CI/CD Pipeline

on:
  workflow_dispatch: 
  push:
    branches: [ "main" ]
    paths:
      - 'quizWeb/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'quizWeb/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: 'quizWeb/package-lock.json'

    - name: Install Dependencies
      run: |
        cd quizWeb
        npm ci

    - name: Build Angular App
      run: |
        cd quizWeb
        npm run build

    # - name: Run Tests
    #   run: |
    #     cd quizWeb
    #     npm run test -- --watch=false --browsers=ChromeHeadless

    - name: Build Docker Image
      run: |
        cd quizWeb
        docker build -t quiz-frontend .

    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push to Docker Hub
      if: github.ref == 'refs/heads/main'
      run: |
        docker tag quiz-frontend ${{ secrets.DOCKER_HUB_USERNAME }}/quiz-frontend:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/quiz-frontend:latest

    - name: Cache npm packages
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node.-