name: Backend CI/CD Pipeline

on:
  workflow_dispatch: 
  push:
    branches: [ "main" ]
    paths:
      - 'quizserver/**'
     
  pull_request:
    branches: [ "main" ]
    paths:
      - 'quizserver/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: |
        cd quizserver
        mvn clean install -DskipTests

    - name: Run Tests
      run: |
        cd quizserver
        mvn test

    - name: Build Docker Image
      run: |
        cd quizserver
        docker build -t quiz-backend .
      
    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push to Docker Hub
      if: github.ref == 'refs/heads/main'
      run: |
        docker tag quiz-backend ${{ secrets.DOCKER_HUB_USERNAME }}/quizserverprojet-frontend:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/quizserverprojet-frontend:latest



    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2